In [4]:
import numpy as np

In [6]:
first = np.array([
    [1,2,3],
    [4,5,6]
])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
first.shape

(2, 3)

In [10]:
second = np.array([
    [7,8,9],
    [10,11,12]
])
second

array([[ 7,  8,  9],
       [10, 11, 12]])

In [14]:
first + second

array([[ 8, 10, 12],
       [14, 16, 18]])

In [18]:
first[1,1]

5

In [23]:
np.concatenate((first,second),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
np.concatenate((first,second),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])