In [1]:
import numpy as np

## 1. Calculate Total Revenue

In [3]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [4]:
qty = np.array([10,5,8,12,3])
qty

array([10,  5,  8, 12,  3])

In [5]:
revenue = prices * qty
revenue

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [6]:
total = revenue.sum()
total

664.62

## 2. Analyze Post Statistics

In [8]:
views = np.array([1000, 500, 800, 1200, 300, 600])
views

array([1000,  500,  800, 1200,  300,  600])

In [11]:
max_views = np.max(views)
max_views

1200

In [13]:
avg_views = np.round(np.average(views), 2)
avg_views

733.33

## 3. Split Order into Chunks

In [20]:
orders = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])
orders

chunks = np.split(orders, 3)
chunks

[array([1001, 1002, 1003]),
 array([1004, 1005, 1006]),
 array([1007, 1008, 1009])]

## 4. Categorize Product Rating

In [25]:
ratings = np.array([4.5, 3.2, 2.8, 5.0, 4.1, 3.9, 2.5, 4.7])
positives = ratings[ratings >= 4.0]
positives

array([4.5, 5. , 4.1, 4.7])

## 5. Calculate Total and Average Quantities

In [26]:
# Column - products (4 products), Row - orders (2 orders)
qty = np.array([[5,3,2,7], 
                [10,6,3,9]])
qty

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [31]:
qty_per_product = np.sum(qty, axis=0)
qty_per_product

array([15,  9,  5, 16])

In [32]:
avg_qty_per_order = np.mean(qty, axis=1)
avg_qty_per_order

array([4.25, 7.  ])

## 6. Calculate Average and Maximum Rating

In [33]:
# Column - category (4 categories), Row - product (3 products)
# Each product is rated by 4 categories
rating = np.array([
    [4.5, 3.2, 2.5, 5.0], 
    [4.3, 3.8, 1.0, 4.8],
    [2.0, 3.6, 4.7, 0.5]
])
rating

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3.8, 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [38]:
avg_rating_per_category = np.round(np.mean(rating, axis=0), 1)
avg_rating_per_category

array([3.6, 3.5, 2.7, 3.4])

In [40]:
max_rating_per_category = np.round(np.max(rating, axis=0), 1)
max_rating_per_category

array([4.5, 3.8, 4.7, 5. ])

## 7. Set every second element in rows after first and find max per row

In [57]:
# Create 2-D array, set every second element in some rows and find max per row
x = np.arange(15, dtype=int).reshape(3, 5)
x[1:, ::2] = -99
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]])

In [58]:
x.max(axis=1)

array([ 4,  8, 13])

## 8. Generate Sample Stock Data (3D array)

In [55]:
companies = ["Google", "Microsoft", "Apple"]
days = ["Mon 1 April", "Tue 2 April"]
types = ["Open", "Close", "High", "Low"]

# 3x2x4
prices = np.round(np.random.random((len(companies), len(days), len(types))), 3)
prices

array([[[0.876, 0.895, 0.085, 0.039],
        [0.17 , 0.878, 0.098, 0.421]],

       [[0.958, 0.533, 0.692, 0.316],
        [0.687, 0.835, 0.018, 0.75 ]],

       [[0.989, 0.748, 0.28 , 0.789],
        [0.103, 0.448, 0.909, 0.294]]])

In [56]:
for i, company in enumerate(companies):
    print(f"{company} prices:")
    for j, day in enumerate(days):
        print(f"\tDay {day}:")
        for k, t in enumerate(types):
            print(f"\t\t{t} Price: {prices[i,j,k]}")    

Google prices:
	Day Mon 1 April:
		Open Price: 0.876
		Close Price: 0.895
		High Price: 0.085
		Low Price: 0.039
	Day Tue 2 April:
		Open Price: 0.17
		Close Price: 0.878
		High Price: 0.098
		Low Price: 0.421
Microsoft prices:
	Day Mon 1 April:
		Open Price: 0.958
		Close Price: 0.533
		High Price: 0.692
		Low Price: 0.316
	Day Tue 2 April:
		Open Price: 0.687
		Close Price: 0.835
		High Price: 0.018
		Low Price: 0.75
Apple prices:
	Day Mon 1 April:
		Open Price: 0.989
		Close Price: 0.748
		High Price: 0.28
		Low Price: 0.789
	Day Tue 2 April:
		Open Price: 0.103
		Close Price: 0.448
		High Price: 0.909
		Low Price: 0.294
