In [1]:
import numpy as np

In [8]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
np.ones((5,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
np.random.random((2,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ]])

In [21]:
np.random.randint(10,20, size=(2,4))

array([[17, 10, 11, 19],
       [19, 10, 14, 17]])

In [22]:
# the same as random()
np.random.uniform(size=(2,4))

array([[0.26455561, 0.77423369, 0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 , 0.61209572, 0.616934  ]])

In [23]:
np.random.uniform(10.0, 20.0, size=(2,4))

array([[19.43748079, 16.81820299, 13.59507901, 14.37031954],
       [16.97631196, 10.60225472, 16.66766715, 16.7063787 ]])

In [24]:
np.random.choice(np.array([1,2,3,4,5]), size=(2,4))

array([[3, 4, 1, 4],
       [5, 2, 3, 5]])

In [26]:
# Generate normally distributed random numbers
rng = np.random.default_rng()
samples = rng.normal(size=25)
samples

array([-0.3405388 ,  1.34095536, -0.5493718 , -0.40794515,  0.71726404,
       -0.60391563,  0.20180401, -1.10126085, -0.38195432, -0.75155208,
        2.54975378,  2.62702116, -0.0699291 , -1.23862071, -0.27744978,
       -0.8708782 ,  0.09982343,  0.21157275, -0.34197806,  0.65227722,
       -0.52825828, -0.02175281, -0.92682506,  1.1916465 ,  0.19462945])